<a href="https://colab.research.google.com/github/goodu001/Outline-Essential-Python-for-Data/blob/main/Essential_python_for_DA_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## numpy
import numpy as np
import pandas as pd

In [ ]:
# numpy : numerical python
friends = ["DumP", "John", "Jane"]

In [ ]:
type(friends)

list

In [ ]:
arr_friends = np.array(friends) # vector in R

In [ ]:
# examscores
scores = [90, 80, 95, 100, 120, 500]
arr_scores = np.array(scores)

In [ ]:
np.mean(arr_scores)

164.16666666666666

In [ ]:
np.median(arr_scores)

97.5

In [ ]:
np.std(arr_scores)

150.6767142667447

In [ ]:
## array 2d
twod_list = [[1,2,3], [4,5,6], [7,8,9]]
arr_2d = np.array(twod_list)

In [ ]:
twod_list[1][2]

6

In [ ]:
arr_2d[0][0]

1

In [ ]:
# martrix multiplication (dot)

mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

In [ ]:
mat1.dot(mat2)

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [ ]:
# prompt: create a student dataframe with 5 column 10 rows using pandas

import pandas as pd
import numpy as np

# Create a sample student DataFrame
num_rows = 10
student_data = {
    'StudentID': np.arange(1, num_rows + 1),
    'Name': ['Student' + str(i) for i in range(1, num_rows + 1)],
    'Age': np.random.randint(18, 22, size=num_rows),
    'Grade': np.random.randint(80, 100, size=num_rows),
    'Major': ['Math', 'CS', 'Physics', 'Biology', 'Chemistry', 'Engineering', 'Economics', 'History', 'English', 'Psychology'][:num_rows]
}

df_students = pd.DataFrame(student_data)
df_students

   StudentID       Name  Age  Grade        Major
0          1   Student1   19     81         Math
1          2   Student2   21     87           CS
2          3   Student3   18     96      Physics
3          4   Student4   18     80      Biology
4          5   Student5   21     85    Chemistry
5          6   Student6   19     97  Engineering
6          7   Student7   18     95    Economics
7          8   Student8   18     94      History
8          9   Student9   18     91      English
9         10  Student10   18     99   Psychology

In [ ]:
df_students["Age"].mean()

18.8

In [ ]:
np.mean(df_students["Age"])

18.8

In [ ]:
df_students.columns

Index(['StudentID', 'Name', 'Age', 'Grade', 'Major'], dtype='object')

In [ ]:
df_students[["StudentID","Name"]].head()

   StudentID      Name
0          1  Student1
1          2  Student2
2          3  Student3
3          4  Student4
4          5  Student5

In [ ]:
df_students.query("Age > 20") ## where clause

   StudentID      Name  Age  Grade      Major
1          2  Student2   21     87         CS
4          5  Student5   21     85  Chemistry

In [ ]:
df_students.query("Major == 'Math' and Grade > 80")[["Name", "Grade", "Major"]]

       Name  Grade Major
0  Student1     81  Math

In [ ]:
# sklearn = machine learning model
# Python ML AI > R

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

In [ ]:
mtcars = pd.read_excel('mtcars.xlsx')
mtcars.head()

,hp,mpg,cyl,disp,drat,wt,qsec,vs,am,gear,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,110,21.0,6,160.0,3.90,2.620,16.46,0,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,110,21.0,6,160.0,3.90,2.875,17.02,0,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93,22.8,4,108.0,3.85,2.320,18.61,1,1,4,...,mpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,110,21.4,6,258.0,3.08,3.215,19.44,1,0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,175,18.7,8,360.0,3.15,3.440,17.02,0,0,3,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# prepare data
x = mtcars.drop("mpg", axis=1)
y = mtcars["mpg"]

In [ ]:
x

,hp,cyl,disp,drat,wt,qsec,vs,am,gear,carb,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,110,6,160.0,3.90,2.620,16.46,0,1,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,110,6,160.0,3.90,2.875,17.02,0,1,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93,4,108.0,3.85,2.320,18.61,1,1,4,1,...,mpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,110,6,258.0,3.08,3.215,19.44,1,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,175,8,360.0,3.15,3.440,17.02,0,0,3,2,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,105,6,225.0,2.76,3.460,20.22,1,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,245,8,360.0,3.21,3.570,15.84,0,0,3,4,...,mpg,cyl,disp,drat,wt,qsec,vs,am,gear,carb
7,62,4,146.7,3.69,3.190,20.00,1,0,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,95,4,140.8,3.92,3.150,22.90,1,0,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,123,6,167.6,3.92,3.440,18.30,1,0,4,4,...,-0.852162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,123,6,167.6,3.92,3.440,18.90,1,0,4,4,...,-0.847551,0.902033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,180,8,275.8,3.07,4.070,17.40,0,0,3,3,...,0.681172,-0.699938,-0.710214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,180,8,275.8,3.07,3.730,17.60,0,0,3,3,...,-0.867659,0.782496,0.88798,-0.712441,NaN,NaN,NaN,NaN,NaN,NaN
13,180,8,275.8,3.07,3.780,18.00,0,0,3,3,...,0.418684,-0.591242,-0.433698,0.091205,-0.174716,NaN,NaN,NaN,NaN,NaN
14,205,8,472.0,2.93,5.250,17.98,0,0,3,4,...,0.664039,-0.810812,-0.710416,0.440278,-0.554916,0.744535,NaN,NaN,NaN,NaN
15,215,8,460.0,3.00,5.424,17.82,0,0,3,4,...,0.599832,-0.522607,-0.591227,0.712711,-0.692495,-0.229861,0.168345,NaN,NaN,NaN
16,230,8,440.0,3.23,5.345,17.42,0,0,3,4,...,0.480285,-0.492687,-0.555569,0.69961,-0.583287,-0.212682,0.206023,0.794059,NaN,NaN
17,66,4,78.7,4.08,2.200,19.47,1,1,4,1,...,-0.550925,0.526988,0.394977,-0.09079,0.427606,-0.656249,-0.569607,0.057534,0.274073,NaN
18,52,4,75.7,4.93,1.615,18.52,1,1,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,65,4,71.1,4.22,1.835,19.90,1,1,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,97,4,120.1,3.70,2.465,20.01,1,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,150,8,318.0,2.76,3.520,16.87,0,0,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,150,8,304.0,3.15,3.435,17.30,0,0,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,245,8,350.0,3.73,3.840,15.41,0,0,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,175,8,400.0,3.08,3.845,17.05,0,0,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,66,4,79.0,4.08,1.935,18.90,1,1,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,91,4,120.3,4.43,2.140,16.70,0,1,5,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,113,4,95.1,3.77,1.513,16.90,1,1,5,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,264,8,351.0,4.22,3.170,14.50,0,1,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,175,6,145.0,3.62,2.770,15.50,0,1,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,335,8,301.0,3.54,3.570,14.60,0,1,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,109,4,121.0,4.11,2.780,18.60,1,1,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# ml workflow
# 1. split data
# 2. train
# 3. score
# 4. evaluate

In [ ]:
# split data
# set.seed(42)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

In [ ]:
# train model
# no free lunch -> experiment
# automl
model = KNeighborsRegressor()
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'wt'

In [ ]:
# prediction
p = model.predict(x_test)

ValueError: could not convert string to float: 'am'

In [ ]:
# evaluate R-squared
model.score(x_test, y_test)

ValueError: could not convert string to float: 'am'